apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}"
stringData:
  FORMIO_ROOT_EMAIL: {{ index .Values "forms-flow-forms" "admin" "email" }}
  FORMIO_ROOT_PASSWORD: {{ index .Values "forms-flow-forms" "admin" "password" }}
  FORMIO_JWT_SECRET: "{{ .Release.Namespace }}-jwt-secret" 
  KEYCLOAK_CLIENTID: {{ index .Values "forms-flow-bpm" "clientid" }}
  KEYCLOAK_CLIENTSECRET: {{ index .Values "forms-flow-bpm" "clientsecret" }}
  WEB_CLIENTID: {{ index .Values "forms-flow-web" "clientid" }}
  WEBSOCKET_ENCRYPT_KEY: "{{ .Values.websocket_encrypt_key }}"
  ADMIN_WEB_CLIENTID: {{ index .Values "forms-flow-web" "clientid" }}
  INSIGHT_API_KEY:  "{{ .Values.insight_api_key }}"
  REDIS_PASSCODE: "{{ .Values.redis_pass_code }}"
  IPAAS_EMBEDDED_API_KEY: "{{ .Values.ipaas.embedded_api_key }}"
  IPAAS_JWT_PRIVATE_KEY: "{{ .Values.ipaas.jwt_private_key }}"
  {{- if .Values.mongodb.enabled }} 
  NODE_CONFIG: '{"mongo":"mongodb://{{ .Values.mongodb.auth.usernames | first }}:{{ .Values.mongodb.auth.passwords | first }}@{{ .Values.mongodb.service.nameOverride }}:{{ .Values.mongodb.service.ports.mongodb }}/{{ .Values.mongodb.auth.databases | first }}"}'
  MONGODB_URI:  {{ ternary (tpl "mongodb://{{ .Values.mongodb.auth.usernames | first }}:{{ .Values.mongodb.auth.passwords | first }}@{{ .Values.mongodb.service.nameOverride }}:{{ .Values.mongodb.service.ports.mongodb }}/{{ .Values.mongodb.auth.databases | first }}" .) "<DEFINE_ME>" .Values.mongodb.enabled | quote }}
  {{- else }}
  MONGODB_URI:  {{ ternary (tpl "mongodb+srv://{{ .Values.mongodb.auth.usernames | first }}:{{ .Values.mongodb.auth.passwords | first }}@{{ .Values.mongodb.service.nameOverride }}/{{ .Values.mongodb.auth.databases | first }}" .) "<DEFINE_ME>" .Values.mongodb.enabled | quote }} 
  NODE_CONFIG: '{"mongo":"mongodb+srv://{{ .Values.mongodb.auth.usernames | first }}:{{ .Values.mongodb.auth.passwords | first }}@{{ .Values.mongodb.service.nameOverride }}/{{ .Values.mongodb.auth.databases | first }}"}'
  {{- end }}